### ISSUE TITLE
Improve code quality using tsconfig

### ISSUE THREAD

**Issue by C0ffeeCode** [BuggyBot/BuggyBot#11]
Set the following settings in tsconfig.json to true:
* noImplicitAny
* strictNullChecks
* strictFunctionTypes
* noImplicitThis
* alwaysStrict
* noImplicitReturns
* strictPropertyInitialization

And fix all issues 😀
And use a new branch!

Finally link 🔗 a Pull Request!

**Comment by Satoqz** [comment]
settings changed, @C0ffeeCode can fix the issues
